services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ProductDB
      POSTGRES_USER: krishna
      POSTGRES_PASSWORD: 458336
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: